# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def main_pods
  pod 'Alamofire', :inhibit_warnings => true
end

target 'BestMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  main_pods
  # Pods for BestMovie

end
